fixes & improvements
WinnerSoftLab/php-adblock-parser pull request #2
Opened 2019-06-27 15:40 UTC by osabinin

2019-06-27 16:16 UTC, komex requested changes
Заодно в AdblockParser::shouldBlock() подними `$directMatchEntry = $this->getSearchEntry($entry);` до начала цикла и убери проверку
```php
if ($rule->isComment() || $rule->isHtml()) {
                continue;
            }
```

2019-06-27 16:16 UTC, komex commented on src/AdblockRule.php
> +            (!$this->domainsIncluded || $this->domainsIncluded && $this->isIncluded($domain))
можно сократить количество условий до:
```php
if ($this->isIncluded($domain) || !$this->isExcluded($domain)) {
```

2019-06-27 16:16 UTC, komex commented on src/AdblockRule.php
> +                throw  new \Exception($e);
Что ты хотел этим сказать?

2019-06-27 16:16 UTC, komex commented on src/AdblockParser.php
> +        $this->rules = $rules;
Сразу же сюда (и в `addRules`) можно добавить фильтрацию по условию как
```php
 if ($rule->isComment() || $rule->isHtml()) {
    continue;
}
```

2019-06-28 08:51 UTC, komex commented on src/AdblockParser.php
> +        $this->rules = $rules;
А тут не нужно фильтровать?

2019-06-28 08:53 UTC, osabinin commented on src/AdblockParser.php
> +        $this->rules = $rules;
@komex мы сюда уже добавляем инициализированный массив правил, которые создались через addRule

2019-06-28 09:19 UTC, komex approved these changes

2019-07-04 17:14 UTC, maxbaldin approved these changes

2019-07-05 14:07 UTC, pavelkdev reviewed
В целом ок

2019-07-05 14:07 UTC, pavelkdev commented on src/AdblockRule.php
> +    private function getDomainsByPlaceholder(string $placeholder, string $rule): array
Если этот метод умеет искать только домены, то зачем он получает на вход placeholder, а не юзает константу класса.
Если он ищет всё что угодно по плейхолдеру, то почему он так странно назван?

2019-07-05 14:07 UTC, pavelkdev commented on src/AdblockRule.php
> +        } else {
можно было бы else {} убрать)

2019-07-05 14:13 UTC, pavelkdev approved these changes

2019-07-05 14:14 UTC, merged