fix isUrl and remove direct match
WinnerSoftLab/php-adblock-parser pull request #4
Opened 2019-07-10 13:55 UTC by osabinin

2019-07-10 13:56 UTC, feliksclickadu approved these changes

2019-07-10 13:59 UTC, komex commented on src/AdblockParser.php
> +            if ($isUrl && $rule->matchUrl($entry)) {
Т.е. если ` $isUrl === false`, то никакой проверки делать не нужно?
Я например, через эту штуку домены и роуты проверяю. Как эти изменения повлияют на проверку?

2019-07-10 15:49 UTC, pavelkdev approved these changes
дпеь

2019-07-10 15:59 UTC, komex requested changes
Нужно переделать работу с правилами: только для домена, только для роута и для их комбинаций

2019-07-15 16:00 UTC, komex requested changes
Еще по хорошему пропускать (не добавлять в список?) правила-комментарии.

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +     * @param bool $containsRoute
Поправь doc.

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +            $entryInfo = $this->getEntryInfo($entry);
Подними это за цикл

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +    public function getEntryInfo($entry): array
type + fix doc

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +        if ($entry[0] === $entry[1] && $entry[0] === '/' || Str::contains($entry, '://')) {
нужна еще проверка на длину строки

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +            $domain = parse_url($entry, PHP_URL_HOST);
Почему бы не делать только один вызов `parse_url` без аргументов, а потом брать нужные тебе части

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +            $parts = array_filter(explode('/', $entry));
в каком случае такое может быть? Разве тут не должен быть только домен?

2019-07-15 16:00 UTC, komex commented on src/AdblockParser.php
> +            'domain' => str_replace('/', '',  $domain),
Зачем?

2019-07-15 16:00 UTC, komex commented on src/AdblockRule.php
> +                || Str::startsWith($this->rule, '|')
разве не `||`?

2019-07-15 16:00 UTC, komex commented on src/AdblockRule.php
> +        $this->isContainsRoute = $this->checkRuleContainsRoute($regex) || !$this->isContainsDomain;
поменяй местами

2019-07-16 12:25 UTC, pavelkdev requested changes
Тесты огонь и либа становится лучше, но ещё есть что доделать.

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockParser.php
> +            'domain' => str_replace('/', '',  $domain),
Ты вероятно имел ввиду 
``
rtrim($domain, '/')
```
? А то реплейс вызывает вопросы

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockParser.php
> +        if ($entry[0] === $entry[1] && $entry[0] === '/' || Str::contains($entry, '://')) {
Кажется что `substr($entry, 0, 2) === '//'` Занимаем меньше места чем `$entry[0] === $entry[1] && $entry[0] === '/'` и сразу понятно что именно мы проверяем.
И оно не упадёт с ворнингом/нотисом если строка имеет 1 символ или пустая

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockParser.php
> +            $parts = array_filter(explode('/', $entry));
Кажется странным такой подход. Есть ли в текущих листах хотя бы 1 запись где это требуется.
Похоже на безопасное программирование которое может привести к ошибкам в каких-то случаях.
Например разве `/adv` это не роут? Но в твоём случае adv станет доменом, а containsRoute - false

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockRule.php
> +        } elseif (Str::contains($rule, '##') || Str::contains($rule, '#@#') || Str::contains($rule, '#?#')) {
А что за Str::contains? Какой-то ларавелевский хелпер?
Что у него под капотом? Не тормознее ли оно чем strpos?

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockRule.php
> +        } elseif (Str::contains($rule, '##') || Str::contains($rule, '#@#') || Str::contains($rule, '#?#')) {
Было бы классно `##` и пр. вынести в константы

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockRule.php
> +
А добавь стрикт тайпы везде плиз

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockParser.php
> +        if ($entry[0] === $entry[1] && $entry[0] === '/' || Str::contains($entry, '://')) {
А ниже ты юзаешь метод либы `Str::startsWith`

2019-07-16 12:25 UTC, pavelkdev commented on src/AdblockRule.php
> +                || Str::startsWith($this->rule, '|')
про `Str::startsWith` тоже вопрос - что там под капотом, не будет ли substr быстрее?

2019-07-16 12:26 UTC, pavelkdev commented
Кажется нам пора перезалить репозиторий и сделать приватным.
После аппрува попроси нас помочь с этим

2019-07-17 15:38 UTC, osabinin commented on src/AdblockParser.php
> +            $parts = array_filter(explode('/', $entry));
в таком случае: test.com/test или в таком com/test

2019-07-17 15:38 UTC, osabinin commented on src/AdblockParser.php
> +            $parts = array_filter(explode('/', $entry));
/adv попадет в предыдущее условие. а все, что не начинается с / мы считаем либо доменом, либо частью домена.

2019-07-17 15:38 UTC, osabinin commented on src/AdblockRule.php
> +                || Str::startsWith($this->rule, '|')
@komex может быть еще такое правило `|test.com|` для полного соответствия урла

2019-07-17 15:38 UTC, osabinin commented on src/AdblockParser.php
> +            'domain' => str_replace('/', '',  $domain),
/ на конце убрать, если есть.

2019-07-17 15:49 UTC, komex commented on src/AdblockParser.php
> +        $path = (string)($urlParts['path'] ?? '');
Для чего приведение?

2019-07-17 15:49 UTC, komex commented on src/AdblockParser.php
> +            $parts = array_filter(explode('/', $entry));
Добавь лимит на количество разбиений (2).

2019-07-17 15:49 UTC, komex commented on src/AdblockParser.php
> +            'domain' => rtrim($domain, '/'),
Но такого же не может быть, когда домен заканчивается на '/'

2019-07-17 16:10 UTC, osabinin commented on src/AdblockParser.php
> +            'domain' => rtrim($domain, '/'),
http://test.com/ будет заканчиваться на /

2019-07-17 17:00 UTC, komex approved these changes

2019-07-18 14:11 UTC, pavelkdev approved these changes

2019-07-18 14:13 UTC, merged